In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('../../../datos_prueba.csv').drop(columns='index')
df1 = df1.sort_values(['ts_kafka', 'message']).reset_index(drop=True)
df1.head()

,ts_kafka,message,messageHex,DL,ICAO,timestamp,OnGround,TC,AircraftType,heading,vertical_rate
0,1734667201534,jDRBFfgAAAAAVVGNlAM=,8c344115f80000000055518d9403,17,344115,2024-12-20 04:00:01.534,1.0,31.0,NaN,NaN,NaN
1,1734667201534,jTR1TZkSAQZYeBI+3PM=,8d34754d991201065878123edcf3,17,34754d,2024-12-20 04:00:01.534,0.0,19.0,NaN,NaN,NaN
2,1734667201534,jTRV1fgjAAIASbigrIs=,8d3455d5f82300020049b8a0ac8b,17,3455d5,2024-12-20 04:00:01.534,0.0,31.0,NaN,NaN,NaN
3,1734667201534,jTRijZkSBIwwBBIuZSo=,8d34628d9912048c3004122e652a,17,34628d,2024-12-20 04:00:01.534,0.0,19.0,NaN,NaN,NaN
4,1734667201534,jTRkGeESjQAAAAD9J6k=,8d346419e1128d00000000fd27a9,17,346419,2024-12-20 04:00:01.534,0.0,28.0,NaN,NaN,NaN

In [3]:
df2 = pd.read_csv('../../../datos_prueba_sp.csv/part-00000-cd46bf22-6d0a-485b-b558-15029ed7cfcd-c000.csv')
df2 = df2.sort_values(['ts_kafka', 'message']).reset_index(drop=True)
df2 = df2[df1.columns]
df2.head()

,ts_kafka,message,messageHex,DL,ICAO,timestamp,OnGround,TC,AircraftType,heading,vertical_rate
0,1734667201534,jDRBFfgAAAAAVVGNlAM=,8c344115f80000000055518d9403,17,344115,2024-12-20T05:00:01.534+01:00,1.0,31.0,NaN,NaN,NaN
1,1734667201534,jTR1TZkSAQZYeBI+3PM=,8d34754d991201065878123edcf3,17,34754d,2024-12-20T05:00:01.534+01:00,0.0,19.0,NaN,NaN,NaN
2,1734667201534,jTRV1fgjAAIASbigrIs=,8d3455d5f82300020049b8a0ac8b,17,3455d5,2024-12-20T05:00:01.534+01:00,0.0,31.0,NaN,NaN,NaN
3,1734667201534,jTRijZkSBIwwBBIuZSo=,8d34628d9912048c3004122e652a,17,34628d,2024-12-20T05:00:01.534+01:00,0.0,19.0,NaN,NaN,NaN
4,1734667201534,jTRkGeESjQAAAAD9J6k=,8d346419e1128d00000000fd27a9,17,346419,2024-12-20T05:00:01.534+01:00,0.0,28.0,NaN,NaN,NaN

In [4]:
(df1 != df2).sum()

ts_kafka            0
message             0
messageHex          0
DL                  0
ICAO                0
timestamp        5804
OnGround         3400
TC               2210
AircraftType     5177
heading          3951
vertical_rate    4653
dtype: int64

In [5]:
df1.isna().sum()

ts_kafka            0
message             0
messageHex          0
DL                  0
ICAO                0
timestamp           0
OnGround         3400
TC               2210
AircraftType     5177
heading          3951
vertical_rate    4653
dtype: int64

In [6]:
df1.timestamp

0       2024-12-20 04:00:01.534
1       2024-12-20 04:00:01.534
2       2024-12-20 04:00:01.534
3       2024-12-20 04:00:01.534
4       2024-12-20 04:00:01.534
                 ...
5799    2024-12-20 04:09:56.146
5800    2024-12-20 04:09:56.655
5801    2024-12-20 04:09:56.655
5802    2024-12-20 04:09:56.655
5803    2024-12-20 04:09:56.655
Name: timestamp, Length: 5804, dtype: object

In [7]:
df2.timestamp

0       2024-12-20T05:00:01.534+01:00
1       2024-12-20T05:00:01.534+01:00
2       2024-12-20T05:00:01.534+01:00
3       2024-12-20T05:00:01.534+01:00
4       2024-12-20T05:00:01.534+01:00
                    ...
5799    2024-12-20T05:09:56.146+01:00
5800    2024-12-20T05:09:56.655+01:00
5801    2024-12-20T05:09:56.655+01:00
5802    2024-12-20T05:09:56.655+01:00
5803    2024-12-20T05:09:56.655+01:00
Name: timestamp, Length: 5804, dtype: object